### PR TITLE
Add edge detect

### PR DESCRIPTION
**Pull request by boriskaiser**
Edge test:

edge_test

### CODE REVIEW

**Comment by SndrL** [comment]
Tried this and did not work :(

**Comment by toddmotto** [comment]
@SndrL What didn't work for you mate?

**Comment by SndrL** [comment]
Well, I included the edge test, and made it do a console.log upon detection. But it just doesnt? I am sure I implemented it the right way because the other detections and their console logs are working fine. Does this work for you? Can anyone verify edge test as working please, because I cannot find my error?

**Comment by boriskaiser** [comment]
@SndrL It's working for me, see:
http://codepen.io/boriskaiser/pen/EVZbvq?editors=001

kgrtwdbseo

**Comment by SndrL** [comment]
First of all I would like to thank you for taking time to look into this issue!

I primarily work on a mac. I have a WIN10 virtual machine for testing.
Your pen, for some reason, is not working? See included screenshot.
This is really strange ...

screen shot 2015-09-30 at 16 15 38

**Comment by Cmac2712** [comment]
This didn't work for us since the Edge user agent string has changed.

Changing the test to: 

conditionizr.add('edge', /Edge\/\d+./i.test(navigator.userAgent));

Fixed the issue.

**Pull request closed without merging**
